// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping_api.proto

package pingv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PingRequest contains no information
type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31d8fe8f48d51168, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

// PingResponse contains a message sent from the server
type PingResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31d8fe8f48d51168, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// PingStreamRequest contains details of the streaming request sent from the
// client
type PingStreamRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingStreamRequest) Reset()         { *m = PingStreamRequest{} }
func (m *PingStreamRequest) String() string { return proto.CompactTextString(m) }
func (*PingStreamRequest) ProtoMessage()    {}
func (*PingStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31d8fe8f48d51168, []int{2}
}

func (m *PingStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingStreamRequest.Unmarshal(m, b)
}
func (m *PingStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingStreamRequest.Marshal(b, m, deterministic)
}
func (m *PingStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingStreamRequest.Merge(m, src)
}
func (m *PingStreamRequest) XXX_Size() int {
	return xxx_messageInfo_PingStreamRequest.Size(m)
}
func (m *PingStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingStreamRequest proto.InternalMessageInfo

func (m *PingStreamRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PingStreamRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// PingStreamResponse contains information about the processing time of the
// ping stream.
type PingStreamResponse struct {
	Count                int32                `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Duration             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PingStreamResponse) Reset()         { *m = PingStreamResponse{} }
func (m *PingStreamResponse) String() string { return proto.CompactTextString(m) }
func (*PingStreamResponse) ProtoMessage()    {}
func (*PingStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31d8fe8f48d51168, []int{3}
}

func (m *PingStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingStreamResponse.Unmarshal(m, b)
}
func (m *PingStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingStreamResponse.Marshal(b, m, deterministic)
}
func (m *PingStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingStreamResponse.Merge(m, src)
}
func (m *PingStreamResponse) XXX_Size() int {
	return xxx_messageInfo_PingStreamResponse.Size(m)
}
func (m *PingStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingStreamResponse proto.InternalMessageInfo

func (m *PingStreamResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PingStreamResponse) GetDuration() *timestamp.Timestamp {
	if m != nil {
		return m.Duration
	}
	return nil
}

// PongStreamRequest contains a count telling the server how many responses
// to stream, and a message to stream back
type PongStreamRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongStreamRequest) Reset()         { *m = PongStreamRequest{} }
func (m *PongStreamRequest) String() string { return proto.CompactTextString(m) }
func (*PongStreamRequest) ProtoMessage()    {}
func (*PongStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31d8fe8f48d51168, []int{4}
}

func (m *PongStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongStreamRequest.Unmarshal(m, b)
}
func (m *PongStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongStreamRequest.Marshal(b, m, deterministic)
}
func (m *PongStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongStreamRequest.Merge(m, src)
}
func (m *PongStreamRequest) XXX_Size() int {
	return xxx_messageInfo_PongStreamRequest.Size(m)
}
func (m *PongStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PongStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PongStreamRequest proto.InternalMessageInfo

func (m *PongStreamRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PongStreamRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// PongStreamResponse contains details of the streaming response.
type PongStreamResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongStreamResponse) Reset()         { *m = PongStreamResponse{} }
func (m *PongStreamResponse) String() string { return proto.CompactTextString(m) }
func (*PongStreamResponse) ProtoMessage()    {}
func (*PongStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31d8fe8f48d51168, []int{5}
}

func (m *PongStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongStreamResponse.Unmarshal(m, b)
}
func (m *PongStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongStreamResponse.Marshal(b, m, deterministic)
}
func (m *PongStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongStreamResponse.Merge(m, src)
}
func (m *PongStreamResponse) XXX_Size() int {
	return xxx_messageInfo_PongStreamResponse.Size(m)
}
func (m *PongStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PongStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PongStreamResponse proto.InternalMessageInfo

func (m *PongStreamResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PongStreamResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// PingPongRequest contains details of a streaming request sent from the
// client.
type PingPongRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingPongRequest) Reset()         { *m = PingPongRequest{} }
func (m *PingPongRequest) String() string { return proto.CompactTextString(m) }
func (*PingPongRequest) ProtoMessage()    {}
func (*PingPongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31d8fe8f48d51168, []int{6}
}

func (m *PingPongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPongRequest.Unmarshal(m, b)
}
func (m *PingPongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPongRequest.Marshal(b, m, deterministic)
}
func (m *PingPongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPongRequest.Merge(m, src)
}
func (m *PingPongRequest) XXX_Size() int {
	return xxx_messageInfo_PingPongRequest.Size(m)
}
func (m *PingPongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingPongRequest proto.InternalMessageInfo

func (m *PingPongRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PingPongRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// PingPongResponse contains details of a streaming response sent from the
// server.
type PingPongResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingPongResponse) Reset()         { *m = PingPongResponse{} }
func (m *PingPongResponse) String() string { return proto.CompactTextString(m) }
func (*PingPongResponse) ProtoMessage()    {}
func (*PingPongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31d8fe8f48d51168, []int{7}
}

func (m *PingPongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPongResponse.Unmarshal(m, b)
}
func (m *PingPongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPongResponse.Marshal(b, m, deterministic)
}
func (m *PingPongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPongResponse.Merge(m, src)
}
func (m *PingPongResponse) XXX_Size() int {
	return xxx_messageInfo_PingPongResponse.Size(m)
}
func (m *PingPongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingPongResponse proto.InternalMessageInfo

func (m *PingPongResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PingPongResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "pingpong.v1.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "pingpong.v1.PingResponse")
	proto.RegisterType((*PingStreamRequest)(nil), "pingpong.v1.PingStreamRequest")
	proto.RegisterType((*PingStreamResponse)(nil), "pingpong.v1.PingStreamResponse")
	proto.RegisterType((*PongStreamRequest)(nil), "pingpong.v1.PongStreamRequest")
	proto.RegisterType((*PongStreamResponse)(nil), "pingpong.v1.PongStreamResponse")
	proto.RegisterType((*PingPongRequest)(nil), "pingpong.v1.PingPongRequest")
	proto.RegisterType((*PingPongResponse)(nil), "pingpong.v1.PingPongResponse")
}

func init() { proto.RegisterFile("ping_api.proto", fileDescriptor_31d8fe8f48d51168) }

var fileDescriptor_31d8fe8f48d51168 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4b, 0x6e, 0xd4, 0x40,
	0x10, 0x86, 0xd5, 0x86, 0x3c, 0x28, 0xc3, 0x24, 0x69, 0xb2, 0x30, 0x56, 0x48, 0x90, 0x57, 0x16,
	0x8b, 0x76, 0x1c, 0x24, 0x90, 0x78, 0x49, 0x84, 0x15, 0x0b, 0x24, 0xcb, 0xa0, 0x2c, 0x10, 0x12,
	0xf2, 0x64, 0x1a, 0xab, 0x05, 0xee, 0x76, 0xdc, 0x6d, 0x1f, 0x80, 0x2b, 0x70, 0x06, 0x36, 0x1c,
	0x85, 0x2d, 0x57, 0xe0, 0x20, 0xa8, 0x1f, 0x66, 0x3c, 0xcc, 0x58, 0x93, 0xd9, 0xb9, 0x5c, 0xf5,
	0xd7, 0x57, 0x7f, 0x55, 0xc3, 0xa4, 0x66, 0xbc, 0xfc, 0x54, 0xd4, 0x8c, 0xd4, 0x8d, 0x50, 0x02,
	0xfb, 0x3a, 0xae, 0x05, 0x2f, 0x49, 0x97, 0x86, 0x47, 0xa5, 0x10, 0xe5, 0x57, 0x9a, 0x14, 0x35,
	0x4b, 0x0a, 0xce, 0x85, 0x2a, 0x14, 0x13, 0x5c, 0xda, 0xd2, 0xf0, 0xc4, 0x65, 0x4d, 0x34, 0x6d,
	0x3f, 0x27, 0x8a, 0x55, 0x54, 0xaa, 0xa2, 0xaa, 0x6d, 0x41, 0x74, 0x07, 0xfc, 0x8c, 0xf1, 0x32,
	0xa7, 0x57, 0x2d, 0x95, 0x2a, 0x8a, 0xe1, 0xb6, 0x0d, 0x65, 0x2d, 0xb8, 0xa4, 0x38, 0x80, 0x9d,
	0x8a, 0x4a, 0x59, 0x94, 0x34, 0x40, 0x0f, 0x50, 0x7c, 0x2b, 0xef, 0xc3, 0xe8, 0x05, 0x1c, 0xe8,
	0xca, 0x77, 0xaa, 0xa1, 0x45, 0xe5, 0xe4, 0x78, 0x02, 0x1e, 0x9b, 0x99, 0xca, 0xad, 0xdc, 0x63,
	0xb3, 0xa1, 0xdc, 0x5b, 0x94, 0x4f, 0x01, 0x0f, 0xe5, 0x0e, 0x77, 0x08, 0x5b, 0x97, 0xa2, 0xe5,
	0xca, 0xb5, 0xb0, 0x01, 0x7e, 0x0c, 0xbb, 0xb3, 0xb6, 0x31, 0xbe, 0x4c, 0x1b, 0xff, 0x2c, 0x24,
	0xd6, 0x17, 0xe9, 0x7d, 0x91, 0xf7, 0xbd, 0xaf, 0xfc, 0x5f, 0x6d, 0xf4, 0x1a, 0x0e, 0x32, 0xf1,
	0xff, 0x88, 0xab, 0x11, 0xe3, 0x83, 0xbe, 0x04, 0x3c, 0x6c, 0xe2, 0x06, 0xbd, 0xbe, 0xd1, 0x67,
	0xb0, 0xa7, 0x8d, 0xea, 0x1e, 0x9b, 0x6f, 0xe9, 0x39, 0xec, 0xcf, 0xc5, 0x9b, 0xa2, 0xcf, 0x7e,
	0xdc, 0x80, 0x1d, 0x2d, 0x7f, 0x95, 0xbd, 0xc1, 0x6f, 0xe1, 0xa6, 0xfe, 0xc4, 0x01, 0x19, 0x3c,
	0x1e, 0x32, 0x38, 0x7d, 0x78, 0x6f, 0x45, 0xc6, 0x22, 0xa3, 0xfd, 0x6f, 0xbf, 0xff, 0x7c, 0xf7,
	0x00, 0xef, 0x26, 0x5d, 0x9a, 0xe8, 0x2a, 0xfc, 0x05, 0x60, 0x7e, 0x3e, 0x7c, 0xbc, 0x24, 0x5d,
	0xd8, 0x79, 0x78, 0x32, 0x9a, 0x77, 0x80, 0xd0, 0x00, 0x0e, 0xa3, 0xbd, 0x1e, 0x90, 0x48, 0x53,
	0xf0, 0x14, 0x3d, 0x8c, 0x91, 0x81, 0x89, 0x31, 0x98, 0x58, 0x03, 0x13, 0x6b, 0x60, 0x62, 0x08,
	0x3b, 0x45, 0xf8, 0x0a, 0x26, 0xfd, 0xca, 0x1d, 0xf0, 0x68, 0x69, 0xfa, 0xc1, 0x31, 0xc3, 0xfb,
	0x23, 0x59, 0x07, 0x3b, 0x36, 0xb0, 0x20, 0xba, 0xdb, 0x3b, 0x5b, 0x04, 0xc6, 0xe8, 0x14, 0x9d,
	0x3f, 0x01, 0xff, 0x52, 0x54, 0xa6, 0x0f, 0xe9, 0xd2, 0x73, 0xbb, 0x59, 0xda, 0x74, 0xb4, 0xc9,
	0xd0, 0x87, 0x6d, 0xfd, 0xbb, 0x4b, 0x7f, 0x7a, 0xe6, 0x94, 0xe4, 0x22, 0xfd, 0x65, 0xbf, 0x3e,
	0x5e, 0xa4, 0xd3, 0x6d, 0xf3, 0xfc, 0x1f, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x61, 0xd7, 0x14,
	0xd0, 0x21, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingAPIClient is the client API for PingAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingAPIClient interface {
	// Ping is a simple request which returns a simple response
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// PingStream accepts a stream of requests, and will return a response
	// containing a count of the requests processed and the time it took to
	// process.
	PingStream(ctx context.Context, opts ...grpc.CallOption) (PingAPI_PingStreamClient, error)
	// PongStream accepts a request stating how many requests to stream back.
	// It will response with a stream until the count is reached and close the
	// connection.
	PongStream(ctx context.Context, in *PongStreamRequest, opts ...grpc.CallOption) (PingAPI_PongStreamClient, error)
	// PingPongStream demonstrates a bidirectional stream where requests are
	// streamed both from the client and the server.
	PingPongStream(ctx context.Context, opts ...grpc.CallOption) (PingAPI_PingPongStreamClient, error)
}

type pingAPIClient struct {
	cc *grpc.ClientConn
}

func NewPingAPIClient(cc *grpc.ClientConn) PingAPIClient {
	return &pingAPIClient{cc}
}

func (c *pingAPIClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/pingpong.v1.PingAPI/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingAPIClient) PingStream(ctx context.Context, opts ...grpc.CallOption) (PingAPI_PingStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PingAPI_serviceDesc.Streams[0], "/pingpong.v1.PingAPI/PingStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingAPIPingStreamClient{stream}
	return x, nil
}

type PingAPI_PingStreamClient interface {
	Send(*PingStreamRequest) error
	CloseAndRecv() (*PingStreamResponse, error)
	grpc.ClientStream
}

type pingAPIPingStreamClient struct {
	grpc.ClientStream
}

func (x *pingAPIPingStreamClient) Send(m *PingStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingAPIPingStreamClient) CloseAndRecv() (*PingStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PingStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingAPIClient) PongStream(ctx context.Context, in *PongStreamRequest, opts ...grpc.CallOption) (PingAPI_PongStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PingAPI_serviceDesc.Streams[1], "/pingpong.v1.PingAPI/PongStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingAPIPongStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PingAPI_PongStreamClient interface {
	Recv() (*PongStreamResponse, error)
	grpc.ClientStream
}

type pingAPIPongStreamClient struct {
	grpc.ClientStream
}

func (x *pingAPIPongStreamClient) Recv() (*PongStreamResponse, error) {
	m := new(PongStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingAPIClient) PingPongStream(ctx context.Context, opts ...grpc.CallOption) (PingAPI_PingPongStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PingAPI_serviceDesc.Streams[2], "/pingpong.v1.PingAPI/PingPongStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingAPIPingPongStreamClient{stream}
	return x, nil
}

type PingAPI_PingPongStreamClient interface {
	Send(*PingPongRequest) error
	Recv() (*PingPongResponse, error)
	grpc.ClientStream
}

type pingAPIPingPongStreamClient struct {
	grpc.ClientStream
}

func (x *pingAPIPingPongStreamClient) Send(m *PingPongRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingAPIPingPongStreamClient) Recv() (*PingPongResponse, error) {
	m := new(PingPongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PingAPIServer is the server API for PingAPI service.
type PingAPIServer interface {
	// Ping is a simple request which returns a simple response
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// PingStream accepts a stream of requests, and will return a response
	// containing a count of the requests processed and the time it took to
	// process.
	PingStream(PingAPI_PingStreamServer) error
	// PongStream accepts a request stating how many requests to stream back.
	// It will response with a stream until the count is reached and close the
	// connection.
	PongStream(*PongStreamRequest, PingAPI_PongStreamServer) error
	// PingPongStream demonstrates a bidirectional stream where requests are
	// streamed both from the client and the server.
	PingPongStream(PingAPI_PingPongStreamServer) error
}

// UnimplementedPingAPIServer can be embedded to have forward compatible implementations.
type UnimplementedPingAPIServer struct {
}

func (*UnimplementedPingAPIServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedPingAPIServer) PingStream(srv PingAPI_PingStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PingStream not implemented")
}
func (*UnimplementedPingAPIServer) PongStream(req *PongStreamRequest, srv PingAPI_PongStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PongStream not implemented")
}
func (*UnimplementedPingAPIServer) PingPongStream(srv PingAPI_PingPongStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PingPongStream not implemented")
}

func RegisterPingAPIServer(s *grpc.Server, srv PingAPIServer) {
	s.RegisterService(&_PingAPI_serviceDesc, srv)
}

func _PingAPI_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingAPIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.v1.PingAPI/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingAPIServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingAPI_PingStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingAPIServer).PingStream(&pingAPIPingStreamServer{stream})
}

type PingAPI_PingStreamServer interface {
	SendAndClose(*PingStreamResponse) error
	Recv() (*PingStreamRequest, error)
	grpc.ServerStream
}

type pingAPIPingStreamServer struct {
	grpc.ServerStream
}

func (x *pingAPIPingStreamServer) SendAndClose(m *PingStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingAPIPingStreamServer) Recv() (*PingStreamRequest, error) {
	m := new(PingStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PingAPI_PongStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PongStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingAPIServer).PongStream(m, &pingAPIPongStreamServer{stream})
}

type PingAPI_PongStreamServer interface {
	Send(*PongStreamResponse) error
	grpc.ServerStream
}

type pingAPIPongStreamServer struct {
	grpc.ServerStream
}

func (x *pingAPIPongStreamServer) Send(m *PongStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PingAPI_PingPongStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingAPIServer).PingPongStream(&pingAPIPingPongStreamServer{stream})
}

type PingAPI_PingPongStreamServer interface {
	Send(*PingPongResponse) error
	Recv() (*PingPongRequest, error)
	grpc.ServerStream
}

type pingAPIPingPongStreamServer struct {
	grpc.ServerStream
}

func (x *pingAPIPingPongStreamServer) Send(m *PingPongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingAPIPingPongStreamServer) Recv() (*PingPongRequest, error) {
	m := new(PingPongRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PingAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pingpong.v1.PingAPI",
	HandlerType: (*PingAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingAPI_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PingStream",
			Handler:       _PingAPI_PingStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PongStream",
			Handler:       _PingAPI_PongStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PingPongStream",
			Handler:       _PingAPI_PingPongStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ping_api.proto",
}
